# Generated by Django 4.2.17 on 2026-01-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profile_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
