# Generated by Django 4.2.17 on 2026-01-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_merge_20260115_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
