# Generated by Django 4.2.17 on 2026-01-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerpolicy', '0001_initial'),
        ('customer', '0003_merge_20260115_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('health', 'Health Insurance Claim'), ('life', 'Life Insurance Claim'), ('motor', 'Motor Insurance Claim'), ('home', 'Home Insurance Claim'), ('travel', 'Travel Insurance Claim'), ('property', 'Property Insurance Claim'), ('business', 'Business Insurance Claim'), ('other', 'Other')], max_length=20)),
                ('incident_date', models.DateField()),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('incident_location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('supporting_documents', models.JSONField(blank=True, default=list)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='customer.customer')),
                ('customer_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='customerpolicy.customerpolicy')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
